### ISSUE TITLE
Failed to import LIFT file.

### ISSUE THREAD

**Issue by KenZook** [sillsdev/web-scriptureforge#109]
Undefined index: name line 86 /var/www/languageforge.org/htdocs/models/languageforge/lexicon/commands/LexProjectCommands.php 
 line , f->lex_import_lift(Array)

JsonRpcServer.php line 67, call_user_func_array(Array, Array)

**Comment by megahirt** [comment]
Hi,

Thanks for trying to import your project on Language Forge and test it out. We recently made some changes to the import process making it more stable. Can you give the import another try and let us know how it goes?

Thanks,

Chris
for the Language Forge dev team

**Comment by KenZook** [comment]
Hi Chris,



We were in Orlando last week. I just tried importing my TestLangProj file.
The good news is it succeeded instead of dying. Much better than before!
Quite a few things are missing. I assume they are areas you haven’t
addressed yet.



I’m puzzled why the two Kalaba language names came up as unlisted
languages. The ldml file lists the language name and abbreviation in

                <special xmlns:palaso="urn://palaso.org/ldmlExtensions/v1">

                                <palaso:abbreviation value="Kal" />

                                <palaso:defaultFontFamily value="Charis
SIL" />

                                <palaso:languageName value="Kalaba" />

                                <palaso:spellCheckingId value="x_kal" />

                                <palaso:version value="2" />

                </special>

The Display Abbreviation is ignoring what was defined ahead of time (above)
and uses the underlying code instead. Also, why is the Display Abbreviation
limited to 4 lowercase letters? We typically want that to start with UC and
may need to be more than 4 letters. Script, Region, and Variant names are
also in <special xmlns:fw="urn://fieldworks.sil.org/ldmlExtensions/v1">.
But this is changing in the new SIL ldml stuff so it’s not FieldWorks
specific (I thnk).



It looks like definition/gloss works the same as WeSay. See WS-301 for
issues with this.



Option lists only show Part of Speech even though the data had more.
FieldWorks uses the lift-ranges file to list the lists we are dealing with.
This is one of the sticky points between WeSay and Flex that should be
solved since WeSay has individual files for each list. So it’s a pain
getting the two programs to use the same lists. I’m not sure what LF is
using.



Observations for ztestmain entry:

Part of Speech is Unknown instead of noun.

None of the Notes fields in sense were imported.

Semantic Domains, Anthropology Categories, Status, and Academic Domains
seem to have been set to list items, but I’m not sure where those lists are
kept.

Reversal entries are missing.

It doesn’t appear that any custom fields are imported.



It had 31 non-important errors during import.

While processing file 'upload_54e260d87cb960.16417126'

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing file 'TestLangProj.lift-ranges'

                                range file 'TestLangProj.lift-ranges' was
not found alongside the 'upload_54e260d87cb960.16417126' file

                processing entry '05c54cf0-4e5a-4bf2-99f8-ec787e4113ac'

                                unhandled field 'Cust Single Line All'

                processing entry '0bfa5f0e-c655-46a3-9047-05bc21547002'

                                unhandled element 'relation'

                processing entry '157edd55-886f-4d91-b009-8e6b49991c85'

                                unhandled element 'relation'

                                processing sense
'3421c175-e7d1-47ea-93ec-7d88bd41cf2e'

                                                unhandled element 'reversal'

                processing entry '1a705846-a814-4289-8594-4b874faca6cc'

                                unhandled note 'bibliography'

                                unhandled note 'restrictions'

                                unhandled element 'variant'

                                unhandled element 'variant'

                                unhandled trait 'Cust Date'

                                unhandled field 'Cust MultiPara'

                                unhandled trait 'Cust Number'

                                unhandled field 'Cust Single Line'

                                unhandled field 'Cust Single Line All'

                                unhandled trait 'Cust Single ListRef'

                                processing multitext 'etymology'

                                                unhandled element 'gloss'

                                                unhandled element 'gloss'

                                                unhandled element 'field'

                                processing sense
'eea9c29f-244f-4891-81db-c8274cd61f0c'

                                                unhandled note
'anthropology'

                                                unhandled note
'bibliography'

                                                unhandled note 'discourse'

                                                unhandled note
'encyclopedic'

                                                unhandled note ''

                                                unhandled note 'grammar'

                                                unhandled note 'phonology'

                                                unhandled note
'restrictions'

                                                unhandled note 'semantics'

                                                unhandled note
'sociolinguistics'

                                                unhandled note 'source'

                                                unhandled element 'reversal'

                                                unhandled element 'reversal'

                                                unhandled trait 'Cust Multi
ListRef'

                                                unhandled trait 'Cust Multi
ListRef'

                                                unhandled element 'subsense'

                                                unhandled element 'subsense'

                                                processing example ''

                                                                unhandled
element 'note'

                                                                unhandled
element 'field'

                                                processing example ''

                                                                unhandled
element 'note'

                processing entry '1c2cbb5d-f0d9-47ff-86af-38d0aae0c765'

                                unhandled element 'variant'

                processing entry '1cfcbd55-1b84-40db-8fbc-c91d1600c531'

                                unhandled element 'variant'

                                unhandled element 'variant'

                processing entry '23151593-0c75-4359-a2bf-6220fc142d79'

                                unhandled field 'Cust Single Line All'

                processing entry '271d373b-e4b7-4c92-80a5-9c36dc8cc810'

                                unhandled element 'variant'

                                unhandled element 'variant'

                processing entry '377f0674-d454-4e37-b2d3-81096fabc84f'

                                unhandled element 'variant'

                processing entry '37e2ccb6-5432-4b80-a599-5dddace292d3'

                                unhandled element 'variant'

                processing entry '386d7575-5dcf-4897-81a2-ae9166928552'

                                processing sense
'7e97c3c0-033f-4984-a0fd-dd3287fc18f1'

                                                unhandled element 'relation'

                processing entry '3afa3967-55fd-49e2-a61d-682bdec60eb2'

                                unhandled element 'relation'

                processing entry '3c861c76-701a-4c25-81d0-88dd6fbdda54'

                                unhandled element 'relation'

                                unhandled media 'recycle.wav' in
pronunciation

                                processing multitext 'pronunciation'

                                                unhandled element 'media'

                processing entry '4a5858f4-3be4-42fc-b23a-e8a6f4d8694e'

                                unhandled element 'variant'

                                unhandled element 'variant'

                                unhandled element 'variant'

                processing entry '4ae1af6e-e4c2-4be5-8047-e9ad0e727c57'

                                unhandled element 'relation'

                processing entry '58a6c6c3-fdbd-4fef-b3de-43e849d6842f'

                                unhandled element 'variant'

                processing entry '5c77efd9-8d14-4f19-a049-162588265cad'

                                processing sense
'9cadf7c5-dd4d-4f32-8430-ce81bf5076a2'

                                                unhandled element 'relation'

                                                unhandled element 'relation'

                processing entry '5d0cdb17-cc47-4c7e-ba9d-9238eb988b5e'

                                unhandled element 'variant'

                                unhandled element 'relation'

                                processing sense
'ab035100-d5f0-4d37-b9af-5aa7f99f8cd9'

                                                unhandled element 'relation'

                processing entry '62798a90-29ce-4de7-8013-b4405e10c3b0'

                                unhandled field 'Cust Single Line All'

                processing entry '631b3df9-81ff-43da-82cf-c323dbc72e80'

                                unhandled field 'Cust Single Line All'

                processing entry '81a73bd1-9c25-4dc0-9396-3c58c7a75395'

                                unhandled element 'variant'

                processing entry '91a74273-3147-4cfe-b5fb-f8b9b8ee257d'

                                processing sense
'9a52a94e-158d-4745-931c-4cdecf587ca8'

                                                unhandled element 'relation'

                processing entry '97e6e1c7-0979-4a06-8891-a84e99b694e5'

                                unhandled element 'relation'

                                unhandled trait 'DoNotUseForParsing'

                processing entry 'a6babda6-6830-4ec0-a363-c7fba14268eb'

                                unhandled element 'relation'

                processing entry 'ad7824e6-474b-45db-b19f-ca4deaed6902'

                                processing sense
'6ff74937-aeed-42ac-ac9c-610c4261b308'

                                                unhandled element 'relation'

                processing entry 'c5b7c026-5f8f-4971-adc1-daf76422632f'

                                unhandled element 'variant'

                processing entry 'd6e17340-dc0f-458a-9fd6-c8de368918d5'

                                unhandled element 'variant'

                                unhandled element 'variant'

                                unhandled element 'variant'

                processing entry 'e322312f-bcfb-42af-91fb-60973c86fea0'

                                unhandled element 'relation'

                processing entry 'ea4b87bf-6525-4e6d-9c9c-a44ff6097e94'

                                unhandled element 'variant'

                processing entry 'f1372812-5d22-469d-aa8d-7465eba15b7a'

                                processing sense
'ad069feb-912f-4408-b15f-3d3e3bde9a5c'

                                                unhandled element 'relation'

                processing entry 'f1895e27-1613-41d4-be06-6b5e075fb768'

                                unhandled element 'variant'

                processing entry 'f764500c-a3cf-4b35-98bf-e39929f488f6'

                                processing sense
'7aceb172-10cb-4cc4-a580-125e79c05f52'

                                                unhandled element 'relation'

                                                unhandled element 'relation'

                                                unhandled element 'relation'

                processing entry 'fd42f793-7fe9-423e-8d7a-a3c280e5e11d'

                                unhandled element 'variant'

                                unhandled element 'variant'

                processing entry 'ffc22c43-a24d-45fb-bc37-1e3e6b1c5560'

                                processing sense
'a74b3d5d-6856-4421-8c1a-c63126f6ef42'

                                                unhandled element 'relation'

                                                unhandled element 'relation'



Ken



*From:* Chris Hirt [mailto:notifications@github.com]
*Sent:* Tuesday, February 10, 2015 12:52 AM
*To:* sillsdev/web-scriptureforge
*Cc:* Ken Zook
*Subject:* Re: [web-scriptureforge] Failed to import LIFT file. (#109)



Hi,

Thanks for trying to import your project on Language Forge and test it out.
We recently made some changes to the import process making it more stable.
Can you give the import another try and let us know how it goes?

Thanks,

Chris
for the Language Forge dev team

—
Reply to this email directly or view it on GitHub
<https://github.com/sillsdev/web-scriptureforge/issues/109#issuecomment-73652874>
.
