### ISSUE TITLE
Error posting comment

### ISSUE THREAD

**Issue by papeh** [sillsdev/web-scriptureforge#112]
Steps:
- Clicked a question to answer on Jamaican Psalm 100
- Highlighted some text
- Entered a comment
- Clicked "Done"
My comment vanished, and the following red dialog appeared:
Oh. Error.
RPC Error
Click for details
Server Status Code 500
Report this bug to the developers
Please copy error above and include screenshot

**Comment by megahirt** [comment]
closed as server issue now resolved.
