### ISSUE TITLE
Import LIFT error

### ISSUE THREAD

**Issue by rowbory** [sillsdev/web-scriptureforge#115]
Undefined index: name line 86 /var/www/languageforge.org/htdocs/models/languageforge/lexicon/commands/LexProjectCommands.php 
 line , f->lex_import_lift(Array)

JsonRpcServer.php line 67, call_user_func_array(Array, Array)

api.php line 23, JsonRpcServer::handle(Sf, CI_Output)

**Comment by megahirt** [comment]
Hi,

Thanks for trying to import your project on Language Forge and test it out. We recently made some changes to the import process making it more stable. Can you give the import another try and let us know how it goes?

Thanks,

Chris
for the Language Forge dev team
