### ISSUE TITLE
Lift Import into language forge

### ISSUE THREAD

**Issue by kentschroeder** [sillsdev/web-scriptureforge#116]
I got  this error when import a lift file into my project for this first time.  the lift file was generated by FLEx 8.

Undefined index: name line 86 /var/www/languageforge.org/htdocs/models/languageforge/lexicon/commands/LexProjectCommands.php 
 line , f->lex_import_lift(Array)

JsonRpcServer.php line 67, call_user_func_array(Array, Array)

api.php line 23, JsonRpcServer::handle(Sf, CI_Output)

**Comment by kentschroeder** [comment]
I still have this problem.  I can not go further until it is resolved

**Comment by megahirt** [comment]
closed as duplicate of sillsdev/web-scriptureforge#117
