### ISSUE TITLE
Importing Lift file into languge forge projecr

### ISSUE THREAD

**Issue by kentschroeder** [sillsdev/web-scriptureforge#117]
I go this error when I tried to import a Lift file generated by FLEx 8.1.

Undefined index: name line 86 /var/www/languageforge.org/htdocs/models/languageforge/lexicon/commands/LexProjectCommands.php 
 line , f->lex_import_lift(Array)

JsonRpcServer.php line 67, call_user_func_array(Array, Array)

api.php line 23, JsonRpcServer::handle(Sf, CI_Output)

**Comment by megahirt** [comment]
Hi Kent,

I assume that your project now imports without a fatal error given that we have recently updated the import code.  Do let me know of your experience importing via email.

Thanks,

Chris
for the Language Forge dev team

**Comment by kentschroeder** [comment]
It is currently working fine…Kent

 

Kent Schroeder 
Software Developer/Language Technology Consultant 
SIL – Africa-Focused Shared Services

Nairobi, Kenya
