### ISSUE TITLE
Bug with my second import, please help

### ISSUE THREAD

**Issue by azulforblue** [sillsdev/web-scriptureforge#119]
This is a project that involves RTL writing and Arabic Script

Undefined index: name line 86 /var/www/languageforge.org/htdocs/models/languageforge/lexicon/commands/LexProjectCommands.php 
 line , f->lex_import_lift(Array)

JsonRpcServer.php line 67, call_user_func_array(Array, Array)

api.php line 23, JsonRpcServer::handle(Sf, CI_Output)

Report this bug to the developers
Please copy error above and include screenshot
Please wait. Importing LIFT file...
Import/Export

    LIFT Import
    LIFT Export
    Settings Import

Import a LIFT File
Drop a LIFT file here

or if you prefer...

**Comment by megahirt** [comment]
Hi,

Thanks for trying to import your project on Language Forge and test it out.  We recently made some changes to the import process making it more stable.  Can you give the import another try and let us know how it goes?

Thanks,

Chris
for the Language Forge dev team
