### ISSUE TITLE
Admin Attempting to Create User Without Password Generates Unclear Error

### ISSUE THREAD

**Issue by ParkeBrown** [sillsdev/web-scriptureforge#121]
This is a minor issue that should be avoided if users fill out forms completely.

1. Logged into Jamaican Psalms project.
2. Navigated to user administration.
3. Clicked "Add New."
4. Filled out all fields and checked "Active User" box, but did not fill out password field.
5. Error pictured below is generated.

![2-5-2015 10-42-45 am](https://cloud.githubusercontent.com/assets/5691814/6063291/182163ec-ad24-11e4-9270-305985b8a744.jpg)

Marking required fields or generating an error message with simpler feedback may address.

**Comment by megahirt** [comment]
closing this as "not applicable" given that the former site admin panel is not longer enabled
