### ISSUE TITLE
New User Account Not Immediately Linked With Project

### ISSUE THREAD

**Issue by ParkeBrown** [sillsdev/web-scriptureforge#122]
Accounts created by the user or the admin are not connected to the project unless admin takes a second step to add the person to the project.

Example 1
1. User goes to jamaicanpsalms.org.
2. Clicks create account.
3. Finishes registration.
4. Login results in the following screen.

![2-5-2015 10-56-50 am](https://cloud.githubusercontent.com/assets/5691814/6070816/bac46610-ad5d-11e4-88e6-e59583ca6340.jpg)

Example 2
1. Admin goes to jamaicanpsalms.org.
2. Admin logs in and creates user account in site administration (https://jamaicanpsalms.com/app/siteadmin). 
3. User logs in.
4. Login results in the above screen.

Admin can correct this by entering project admin and adding user to the project manually. 

We're investigating how many users this has affected, but know that the team has experienced this issue this week with some users.

**Comment by megahirt** [comment]
Hi Parke,

Thanks for reporting this issue.  There are a number of of "behind the scenes" upgrades that have taken place recently, and one of them affected this feature for jamaican psalms.  This is now fixed.  Thanks for reporting it!
