### ISSUE TITLE
Attempting to remove member results in error

### ISSUE THREAD

**Issue by ParkeBrown** [sillsdev/web-scriptureforge#123]
1. Log into site as admin.
2. Navigate to project user admin (https://jamaicanpsalms.com/app/sfchecks/51fa387956dd85d1714e0ff8#/settings).
3. Select check box next to user.
4. Click "Remove Members."
5. Error message below appears and member remains.

![2-6-2015 11-01-08 am](https://cloud.githubusercontent.com/assets/5691814/6082509/fcef7f88-adef-11e4-8d26-462627b7b426.jpg)

**Comment by megahirt** [comment]
Thanks for reporting this Parke.  I will take care of this on Monday.

- Chris

**Comment by megahirt** [comment]
fixed in 14478fc0402d45ed5eb7d1b11de44eefc6dd288f (will be deployed shortly)
