### ISSUE TITLE
Select limited verse range not working for me

### ISSUE THREAD

**Issue by makerling** [sillsdev/web-scriptureforge#127]
I'm testing out Scriptureforge for a presenting it at a Language Technology in Eurasia workshop. I tried the "Select limited verse range" feature in the "Add New Text" menu. With the help of the Paratext plugin I generated a .txt file of Gen 7. I imported the file then tried the "Select limited verse range" feature. I chose to limit it From Gen7:1 To Gen7:10. After clicking Save, the only the title of the text appeared, no verses. I also tested it with a chapter from an English text, with the same results to verify if it is an encoding issue. I am using the Firefox browser on a Mint Linux machine. 
Wondering if this feature is just a placeholder or if it is supposed to work. I'm attaching the usx/txt file. 

Thanks,

Stevan
[GEN7.txt](https://github.com/sillsdev/web-scriptureforge/files/197568/GEN7.txt)

**Comment by megahirt** [comment]
Dear Stevan,

I confirmed that this is a bug and was able to reproduce it with the Gen text you uploaded.  Unfortunately our dev team is entering a 2 week conference / Thai national holiday period in which no developers will be in the office.  We'll make this a priority to fix once we return to the office and before you present at the May 1 conference.  Feel free to check in by April 23.

Thanks,

Chris

**Comment by makerling** [comment]
Thanks. Not a huge priority for as I'm just testing the webapp in
preparation for a training workshop. But hope your conference and time off
go well!

Stevan
On Apr 1, 2016 7:43 AM, "Chris Hirt [Masked]" <
FWD-737QTYSMENAIYCQANIQDDYBDGACOOANZDFBALAAY4UAEMAKYHPECAYYFEFGCGMBBMRPE2JBMKZHKQE4PGGJWQ3JCXUMKUHUKASZAQIQZY5JWY4JDIJSQFVDNQI6EC7CIKJABCYAAJIESUAB5ABMUARKAFNACKQCLKE4V4ID3EBNSALTCAEGCL5IIPQQCAABA@opayq.com>
wrote:

**Comment by rmunn** [comment]
https://github.com/sillsdev/web-scriptureforge/commit/b1c48f147133fd183dead0c0e077699ba6d59e7a should be a fix for this bug. We'll test it, then once we've deployed the fix we'll close this issue.

**Comment by megahirt** [comment]
This fix has shipped.
