### ISSUE TITLE
In Dev and Prod, Deleting user results in error code and no text or comments being displayed.

### ISSUE THREAD

**Issue by ParkeBrown** [sillsdev/web-scriptureforge#82]
To Reproduce:
1. Create test user.
2. Add comment with test user (either as the sole commenter on a question or alongside other commenters).
3. Log out and log in as admin.
4. Delete user in admin tools.
5. Navigate back to question with comment.

User Comments Twice
![jp - admin delete user 1](https://f.cloud.github.com/assets/5691814/1450301/4b33c462-4279-11e3-915d-80884f5befaf.jpg)

User Deleted Resulting in Error and No Display of Review Copy
![jp - admin delete user 2](https://f.cloud.github.com/assets/5691814/1450303/4b3457ba-4279-11e3-9491-ad6233af7b78.jpg)

User Comments Alongside Other Users
![jp - admin delete user alongside others 1](https://f.cloud.github.com/assets/5691814/1450302/4b342b00-4279-11e3-9517-0072f37fa079.jpg)

User Deleted Resulting in Error and No Display of Review Copy or Comments by Others
![jp - admin delete user alongside others 2](https://f.cloud.github.com/assets/5691814/1450304/4b373160-4279-11e3-94dd-1c4ff53dfe8d.jpg)

See example here:
http://jamaicanpsalms.dev.scriptureforge.org/app/sfchecks#/project/5253cf1e96f2f8e018975214/5253cf8196f2f8e118f82529/5253d0aa96f2f8a81ce08b91

**Comment by megahirt** [comment]
closed because we are no longer keeping track of "enhancements" on our issue tracker.  The place to track those are on the trello board.  https://trello.com/b/HQ2fRqfl/checking-web-app
