### ISSUE TITLE
Ability to broadcast changes to all users in the community simultaneously

### ISSUE THREAD

**Issue by ParkeBrown** [sillsdev/web-scriptureforge#85]
"I see the ability to message individual users, but not the ability to broadcast to all users in the community without selecting them one-by-one. A 'select all' button would take care of that feature." - Randall

**Comment by megahirt** [comment]
closed because we are no longer keeping track of "enhancements" on our issue tracker.  The place to track those are on the trello board.  https://trello.com/b/HQ2fRqfl/checking-web-app
