### ISSUE TITLE
Announcements pane on user dashboard for manager announcements

### ISSUE THREAD

**Issue by ParkeBrown** [sillsdev/web-scriptureforge#86]
"Additionally we’d envisioned an 'announcements' pane on the user dashboard with managers having the ability to post messages that a member would see after logging in." - Randall

**Comment by megahirt** [comment]
closed because we are no longer keeping track of "enhancements" on our issue tracker.  The place to track those are on the trello board.  https://trello.com/b/HQ2fRqfl/checking-web-app
